# Generated by Django 6.0.3 on 2026-03-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_cart_id_alter_cartitem_id_alter_collection_id_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="store_custo_last_na_2e448d_idx",
            old_name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customer",
        ),
    ]
