# Generated by Django 6.0.3 on 2026-03-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_customer_store_custo_last_na_2e448d_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('Collection 01')
            ""","""
            DELETE FROM store_collection WHERE title = 'Collection 01'
            """
        )
    ]
